Feature/#129 place detail UI
Team-Recordy/Recordy-Android pull request #132
Opened 2024-10-05 08:44 UTC by nagaeng

## 📌 PR 요약

🌱 작업한 내용
- 장소 detail ui 끝 ....

🌱 PR 포인트
- 

## 📸 스크린샷

https://github.com/user-attachments/assets/30f4debf-60b9-40f5-af6c-127b74e8f6f0

https://github.com/user-attachments/assets/55b6eda8-0293-4f47-aaa3-d471f2bc9f24

## 📮 관련 이슈
- Resolved: #129

2024-10-10 06:39 UTC, cacaocoffee approved these changes
수고하셨어요 포크떠서 확인해봤는데 화면 ui 도 잘맞는거 같네요

2024-10-10 06:39 UTC, cacaocoffee commented on feature/detail/src/main/java/com/record/detail/DetailpageViewModel.kt
> +    fun fetchPlaceInfo() {
이 함수는 추후 API 연결을 위한건가요?

2024-10-10 07:45 UTC, seohee0925 approved these changes
Hilt까지 야물딱지게 넘 잘하셨네요 
수고했어용

2024-10-10 08:01 UTC, nagaeng commented on feature/detail/src/main/java/com/record/detail/DetailpageViewModel.kt
> +    fun fetchPlaceInfo() {
정답입니다~~

2024-10-10 12:53 UTC, Sangwook123 requested changes
고생했어요~ 너무 잘했네요 하나만 수정 부탁

2024-10-10 12:53 UTC, Sangwook123 commented on feature/detail/src/main/java/com/record/detail/screen/ListScreen.kt
> +fun ExhibitionItem(name: String, startDate: Date, endDate: Date, onButtonClick: () -> Unit) {
Date타입은 Stable하지 않기때문에 컴포저블 인자로 적절하지 않은것같아유 String으로 바꿔서 해보죠 !

2024-10-11 09:45 UTC, nagaeng commented on feature/detail/src/main/java/com/record/detail/screen/ListScreen.kt
> +fun ExhibitionItem(name: String, startDate: Date, endDate: Date, onButtonClick: () -> Unit) {
넷 금방 수정해서 올리겠습니다!!

2024-10-13 14:10 UTC, Sangwook123 approved these changes
굿! 머지합시다

2024-10-13 15:50 UTC, merged