Feature/#130 search UI
Team-Recordy/Recordy-Android pull request #135
Opened 2024-10-10 19:39 UTC by seohee0925

## 📌 PR 요약
검색화면 UI 및 기능 구현

🌱 작업한 내용
- 검색 기본 화면
- 검색 중 화면
- 검색 완료 화면

🌱 PR 포인트
- 검색 결과 없음 위치 조정 필요

## 📸 스크린샷

https://github.com/user-attachments/assets/24a1d3eb-01d1-428a-9269-0a6e232a8caf

## 📮 관련 이슈
- Resolved: #130

2024-10-13 14:14 UTC, Sangwook123 requested changes

2024-10-13 14:14 UTC, Sangwook123 commented on feature/search/src/main/java/com/record/search/SearchViewModel.kt
> +class SearchViewModel : ViewModel() {
BaseViewmodel 활용해서 mvi 패턴으로 변경 부탁드립니다

2024-10-14 08:04 UTC, seohee0925 commented on feature/search/src/main/java/com/record/search/SearchViewModel.kt
> +class SearchViewModel : ViewModel() {
넵 오늘 중으로 수정하겠습니다!

2024-10-14 14:30 UTC, Sangwook123 requested changes

2024-10-14 14:30 UTC, Sangwook123 commented on feature/search/src/main/java/com/record/search/SearchState.kt
> +    val filteredItems: List<Exhibition> = emptyList(),
ImmutableList로 변경해주세요 ! compose 컴파일러는 List 타입을 Stable로 간주하지 않아서 불필요한 리컴포지션이 발생할 수 있습니다.

2024-10-14 16:15 UTC, seohee0925 commented on feature/search/src/main/java/com/record/search/SearchState.kt
> +    val filteredItems: List<Exhibition> = emptyList(),
변경했습니다! 감사합니다 😄

2024-10-16 12:51 UTC, Sangwook123 approved these changes
머지합시다 고생하셨어요 ~!

2024-10-16 14:04 UTC, merged