Feature/#6 component progressbar button
Team-Recordy/Recordy-Android pull request #45
Opened 2024-07-03 16:06 UTC by seohee0925

## 📌 PR 요약

🌱 작업한 내용
- progress bar 컴포넌트 작업
- button 컴포넌트 작업

🌱 PR 포인트
- progress bar는 완성도 숫자를 입력할 경우 그에 맞춰서 변경됩니다.
- button은 글씨와 enabled 여부를 parameter로 받아서 그에 맞는 버튼으로 변경됩니다.
```
RecordyButton(
       text = "완료",
       enabled = true,
       onClick = {}
)

RecordyProgressBar(
        50
)
```

## 📸 스크린샷

https://github.com/Team-Recordy/Recordy-Android/assets/102652293/dfc1dc39-e7cb-48d7-9de9-16b6a06f70e9

![스크린샷 2024-07-04 005857](https://github.com/Team-Recordy/Recordy-Android/assets/102652293/f2350a40-0cbb-4aa6-b02f-0338ede8a7f8)

## 📮 관련 이슈
- Resolved: #6

2024-07-03 23:53 UTC, cacaocoffee approved these changes
수고하셨어요 다만 Int로 전체의 몇 %인지 조금 번거롭지 않을까 걱정이 들어서 리뷰남겼어요!

2024-07-03 23:53 UTC, cacaocoffee commented on core/designsystem/src/main/java/com/record/designsystem/component/progressbar/RecordyProgressBar.kt
> +    completionRatio: Int,
Int 보단 Flaot 로 받아서 
사용처에서 3/4 와 같이 받는건 어떨까 싶어요

2024-07-03 23:53 UTC, cacaocoffee commented on core/designsystem/src/main/java/com/record/designsystem/component/progressbar/RecordyProgressBar.kt
> +    )
어려웠을 텐데 수고하셨어요!

2024-07-03 23:53 UTC, cacaocoffee commented on core/designsystem/src/main/java/com/record/designsystem/component/button/RecordyButton.kt
> +            style = RecordyTheme.typography.button1,
```kotlin
    style = RecordyTheme.typography.button1.copy(color = if (enabled) RecordyTheme.colors.gray09 else RecordyTheme.colors.gray04),
```
    
   이런식으로 바꾸면 contentColor 로 안줘도 돼요! 
   그냥 참고용으로  넣어둡니다. (혹시 나중에 content 여러개 들어가는거 에서 헤매실까봐..)

2024-07-03 23:53 UTC, cacaocoffee commented on core/designsystem/src/main/java/com/record/designsystem/component/button/RecordyButton.kt
> +        shape = RoundedCornerShape(12.dp),
```kotlin 
shape =  MaterialTheme.shapes.medium,
``` 

이렇게 상수를 안쓰고 사용할 수 도 있습니다!

2024-07-03 23:58 UTC, cacaocoffee commented on core/designsystem/src/main/java/com/record/designsystem/component/button/RecordyButton.kt
> +        shape = RoundedCornerShape(12.dp),
성능적 측면에서는
RoundedCornerShape(12.dp): 호출될 때마다 새로운 인스턴스를 생성
MaterialTheme.shapes.medium: 테마에 이미 정의되어 있는 인스턴스를 재사용하기 떄문에  

1. 메모리 적 측면에서 좋아요 ( 새로운 인스턴스를 안만들어도 되니!)
2. 리컴포지션의 대상이 된다. ( 인스턴스가 생성될 때 마다 리컴포지션이 일어난다고하네요)
   상수값은 인스턴스 생성을 통한 직접적인 계산이 들어가기에 , 리컴포지션 시마다 새로 계산돼요 
   그렇기에 미리정의된 걸 사용하는게 좋아요

2024-07-04 07:29 UTC, Sangwook123 requested changes
고생하셨습니다. 몇 가지 수정사항 있습니다.

2024-07-04 07:29 UTC, Sangwook123 commented on core/designsystem/src/main/java/com/record/designsystem/component/button/RecordyButton.kt
> +        shape = RoundedCornerShape(12.dp),
RoundedCornerShape는 기본적으로 불변성 원칙에 따르기 때문에 상태 변화시 리컴포지션 되지 않습니다! 따라서 지금처럼 사용해도 괜찮습니다 !

2024-07-04 07:29 UTC, Sangwook123 commented on core/designsystem/src/main/java/com/record/designsystem/component/button/RecordyButton.kt
> +        ),
```suggestion
        colors = ButtonDefaults.buttonColors(
            containerColor = RecordyTheme.colors.main,
            contentColor = RecordyTheme.colors.gray09,
            disabledContainerColor = RecordyTheme.colors.gray08,
            disabledContentColor = RecordyTheme.colors.gray04.
        ),
```

2024-07-04 07:29 UTC, Sangwook123 commented on core/designsystem/src/main/java/com/record/designsystem/component/progressbar/RecordyProgressBar.kt
> +            .height(6.dp)
여기 높이가 피그마랑 다른것같습니다 !

2024-07-04 11:21 UTC, seohee0925 commented on core/designsystem/src/main/java/com/record/designsystem/component/button/RecordyButton.kt
> +            style = RecordyTheme.typography.button1,
우와 이런 방법이 있군요
바로 적용해보겠습니다!

2024-07-04 11:24 UTC, seohee0925 commented on core/designsystem/src/main/java/com/record/designsystem/component/progressbar/RecordyProgressBar.kt
> +            .height(6.dp)
헉 감사합니다

2024-07-04 11:36 UTC, cacaocoffee commented on core/designsystem/src/main/java/com/record/designsystem/component/button/RecordyButton.kt
> +        shape = RoundedCornerShape(12.dp),
헉 잘못된 정보를 찾았나봐요

2024-07-04 12:05 UTC, seohee0925 commented on core/designsystem/src/main/java/com/record/designsystem/component/button/RecordyButton.kt
> +        shape = RoundedCornerShape(12.dp),
새로운 사실들을 알았네요.. 두분 다 답변 감사합니다!

2024-07-04 12:06 UTC, seohee0925 commented on core/designsystem/src/main/java/com/record/designsystem/component/progressbar/RecordyProgressBar.kt
> +    completionRatio: Int,
오케 해볼게요!!!!

2024-07-04 12:15 UTC, seohee0925 commented on core/designsystem/src/main/java/com/record/designsystem/component/progressbar/RecordyProgressBar.kt
> +    completionRatio: Int,
```
RecordyProgressBar(
        completionRatioNumerator = 3,
        completionRatioDenominator = 4,
    )
```
이런 식으로 3/4 받도록 해서 75% 되도록 수정했습니당 땡큐

2024-07-04 18:23 UTC, Sangwook123 approved these changes
고생하셨습니다 ~~!  머지고고

2024-07-04 18:24 UTC, merged