Feature/#7 component textfield
Team-Recordy/Recordy-Android pull request #46
Opened 2024-07-03 17:56 UTC by nagaeng

## 📌 PR 요약

🌱 작업한 내용
- textfield 컴포넌트 만들었어요 !

🌱 PR 포인트
- Focusing stroke : error (x) main 컬러 / error (o) alert 컬러
- 최대 글자 수(maxlength) 설정 및 입력되는 만큼 n/10 글자수 띄우기
- 4개의 sealed class로 상태를 분류함.
- 선언부 errorState에서의 인자값을 변경시키는 방식으로 상태별로 확인해야 합니다~! 
 

## 📸 스크린샷
**Focus 됐을 때**
<img width="191" alt="Focusing" src="https://github.com/Team-Recordy/Recordy-Android/assets/109855280/23390565-8fd1-45ee-8fb7-48a2e91cc0b0">

**아무것도 입력되지 않았을 **
<img width="186" alt="InputtingError" src="https://github.com/Team-Recordy/Recordy-Android/assets/109855280/350d3ea0-7456-48fa-9854-f811295fbe46">

**사용가능한 닉네임/글자수 세기**
<img width="186" alt="SuccessError" src="https://github.com/Team-Recordy/Recordy-Android/assets/109855280/072ec41e-d4f4-47d5-84d2-848691cd14a7">

**사용 불가능한 닉네임**
<img width="188" alt="ValidationError" src="https://github.com/Team-Recordy/Recordy-Android/assets/109855280/0c1f4149-ed15-47e0-a316-5b6d8a5ac7c2">

## 📮 관련 이슈
- Resolved: #7

2024-07-03 23:28 UTC, cacaocoffee approved these changes
늦은 시간까지 수고하셨어요!

![image](https://github.com/Team-Recordy/Recordy-Android/assets/75840431/95875c67-ed18-4dbd-822c-54342838d0a9)

이와 같이 줄이 넘어갔을 때는 어떻게 대처할지 디자인과 논의가 필요해보여요

또한, 조금 다듬으면
![image](https://github.com/Team-Recordy/Recordy-Android/assets/75840431/3620c447-998f-4ef6-8640-be3196c2a2b6)

와 같은 컴포넌트에서도 사용할 수 있을거 같네요

2024-07-03 23:28 UTC, cacaocoffee commented on core/designsystem/src/main/java/com/record/designsystem/component/textfield/RecordyValidateTextfield.kt
text 상수화에 대해서 어떻게 생각하시나요

ValidateResult 의 에러 경우 에러메시지에 대해서 상수화 할 수 있을거 같아요

2024-07-03 23:28 UTC, cacaocoffee commented on core/designsystem/src/main/java/com/record/designsystem/component/textfield/RecordyValidateTextfield.kt
> +            .padding(horizontal = 16.dp)
현재 padding을 직접적으로 사용하고 있습니다.

뷰에서 화면에 따라 전체적으로 패딩을 줬을 때 번거로워 질 수 있으니 parameter에 
```kotlin
padding = PaddingValues(horizontal = 16.dp),
```
과 같이두고 이를 참조해서 사용하시는 건 어떨까요?

2024-07-03 23:28 UTC, cacaocoffee commented on core/designsystem/src/main/java/com/record/designsystem/component/textfield/RecordyValidateTextfield.kt
> +}
![image](https://github.com/Team-Recordy/Recordy-Android/assets/75840431/7e8ddc73-121f-4c0a-8344-cd89ed5673cc)

현재 피그마의 디자이 UI 끄적끄적에 있는 부분입니다. 

위와 같은 각각에 상태에는 

직접 빌드하고 확인하기 보단 Preview를 여러 상태에 따라 선언하여 
한번에 볼 수 있게 만들어 놓으면 다음 작업, PR 에 올릴 스크린 샷 찍기 편할거 같아요! 
물론 제 개인적 생각입니다.

2024-07-04 07:51 UTC, Sangwook123 requested changes
고생하셨습니다. 변경사항 요청 남깁니다.

2024-07-04 07:51 UTC, Sangwook123 commented on core/designsystem/src/main/java/com/record/designsystem/component/textfield/RecordyValidateTextfield.kt
> +                    ValidateResult.OverlapError -> "이미 사용중인 닉네임이에요"
재사용성을 위해서 메시지도 파라미터로 받는게 나을 것 같습니다.

2024-07-04 07:51 UTC, Sangwook123 commented on core/designsystem/src/main/java/com/record/designsystem/component/textfield/RecordyValidateTextfield.kt
> +                .background(color = RecordyTheme.colors.gray08, shape = MaterialTheme.shapes.medium)
shape가 MaterialTheme에 종속될경우, MaterialTheme이 변경될경우 의도하지 않은 ui변경이 생길 가능성이 있습니다. roundedcornershape사용하는 편이 나을 것 같아요

2024-07-04 18:23 UTC, Sangwook123 approved these changes
굿굿 머지합시다 !

2024-07-05 00:34 UTC, merged