Feature/#52 mypage followlist
Team-Recordy/Recordy-Android pull request #65
Opened 2024-07-10 17:53 UTC by seohee0925

## 📌 PR 요약

🌱 작업한 내용
- 마이페이지 팔로우, 팔로잉 리스트 제작했어요 
- 팔로우, 팔로잉 클릭할 때마다 `SideEffect`로 상태 전달합니다

🌱 PR 포인트
- 마이페이지 팔로우, 팔로잉 리스트 제작했어요
- UserData는 아래와 같아요
```
data class UserData(
    val id: Int,
    val profileImage: String,
    val name: String,
    val isFollowing: Boolean,
)
```

## 📸 스크린샷
https://github.com/Team-Recordy/Recordy-Android/assets/102652293/27bed394-c41b-4677-b476-d3fb37b836d7

## 📮 관련 이슈
- Resolved: #52

2024-07-10 19:35 UTC, cacaocoffee requested changes
수고하셨어요. 컨플릭트 나는 부분 확인하셔야할거 같아요

2024-07-10 19:35 UTC, cacaocoffee commented on core/designsystem/src/main/java/com/record/designsystem/component/button/FollowButton.kt
> +}
텍스트와 버튼의 컬러를 하나로 Pair 를 활용해서 받는건 생각 못해봤는데 잘 살펴보고 가요

2024-07-10 19:35 UTC, cacaocoffee commented on core/designsystem/src/main/java/com/record/designsystem/component/button/RecordyButtonLarge.kt
> +fun RecordyButtonLarge(
이름 변경으로 인해 conflict가 난거 같아요 rebase를 통해 하나로 통일하셔야할 거 같아요
 이미 develop 에 올라온 버튼의 경우 다른 분들이 사용하고 계실 수 있으니 수정을 피하는게 좋다고 생각이 드네요

2024-07-11 13:03 UTC, lsakee reviewed
고생하셨어요

2024-07-11 13:03 UTC, lsakee commented on core/designsystem/src/main/java/com/record/designsystem/component/button/FollowButton.kt
> +        shape = RoundedCornerShape(8.dp),
요러한 부분들 staless하게 호이스팅해도 좋을 것 같습니다

2024-07-11 13:03 UTC, lsakee commented on core/designsystem/src/main/java/com/record/designsystem/component/button/RecordyButtonMedium.kt
> +        onClick = onClick,
CustomClickable만들어 놓은 거 사용해서 리플같은 것도 고료하면 더욱 좋을거 같습니다.

2024-07-11 15:23 UTC, seohee0925 commented on core/designsystem/src/main/java/com/record/designsystem/component/button/RecordyButtonMedium.kt
> +        onClick = onClick,
넵 감사합니당

2024-07-11 15:23 UTC, seohee0925 commented on core/designsystem/src/main/java/com/record/designsystem/component/button/FollowButton.kt
> +        shape = RoundedCornerShape(8.dp),
감사합니다!!!

2024-07-11 15:23 UTC, seohee0925 commented on core/designsystem/src/main/java/com/record/designsystem/component/button/RecordyButtonLarge.kt
> +fun RecordyButtonLarge(
해결완료 감사합니당

2024-07-11 18:14 UTC, Sangwook123 approved these changes
LGTM

2024-07-11 18:18 UTC, cacaocoffee approved these changes

2024-07-11 18:44 UTC, closed without merging